new TypeIt("#credit", {
    lifeLike: false,
    speed: 0
})
  .type("© ")
  .pause(312)
  .type("2")
  .pause(178)
  .type("0")
  .pause(97)
  .type("2")
  .pause(588)
  .type("5")
  .pause(775)
  .type(" ")
  .pause(471)
  .type("-")
  .pause(477)
  .type(" ")
  .pause(592)
  .type("W")
  .pause(300)
  .type("O")
  .pause(172)
  .type("R")
  .pause(429)
  .type("K")
  .pause(429)
  .type("F")
  .pause(402)
  .type("L")
  .pause(531)
  .type("O")
  .pause(454)
  .type("W")
  .pause(393)
  .type(" ")
  .pause(153)
  .type("T")
  .pause(131)
  .type("E")
  .pause(591)  
    .type("S")
  .pause(591)  
    .type("T")
  .pause(591)
    .type("I")
    .pause(591)
    .type("N")
    .pause(591)
    .type("G")
    .pause(591)
    .type(" ")
    .pause(591)
    .type("T")
    .pause(591)
    .type("E")
    .pause(591)
    .type("A")
    .pause(591)
    .type("M")
  .pause(153)
  .move(null, { to: "END" })
  .pause(500)
  .type(".")
  .go();
